title: MAYANK PRATAP SINGH
logo: https://github.com/mayankpratap202005-max/MAYANK-PRATAP-SINGH-RESUME/blob/effacb2e24c3255710cf1604e1edad9f9142d2bb/VRINDAVAN%20PHOTO.jpg
theme: jekyll-theme-minimal
Description: COMPUTER SCIENCE ENGINEERING
